In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[-0.21322817,  0.05068486, -0.80992808],
       [-0.32968206,  0.55346776, -0.96450958],
       [ 1.26232278,  1.03425114,  0.87505786],
       [-0.06212774,  0.75160796,  0.66413303]])

In [5]:
data_frame = pd.DataFrame(data)

In [7]:
# data_frame = pd.Series(data) data_frame is not one dimensional but series

In [8]:
data_frame

          0         1         2
0 -0.213228  0.050685 -0.809928
1 -0.329682  0.553468 -0.964510
2  1.262323  1.034251  0.875058
3 -0.062128  0.751608  0.664133

In [9]:
type(data_frame)

pandas.DataFrame

In [12]:
type(data_frame[0]) # when we make it one dimensional it became series

pandas.Series

In [13]:
new_df = pd.DataFrame(data,index=["Atil","Zeynep","Atlas","Mehmet"],columns= ["Salary","Age","Seniority"])

In [14]:
new_df

          Salary       Age  Seniority
Atil   -0.213228  0.050685  -0.809928
Zeynep -0.329682  0.553468  -0.964510
Atlas   1.262323  1.034251   0.875058
Mehmet -0.062128  0.751608   0.664133

In [15]:
new_df["Age"]

Atil      0.050685
Zeynep    0.553468
Atlas     1.034251
Mehmet    0.751608
Name: Age, dtype: float64

In [17]:
# new_df["Atil"] we can use columns to access data

In [18]:
new_df["Salary"]

Atil     -0.213228
Zeynep   -0.329682
Atlas     1.262323
Mehmet   -0.062128
Name: Salary, dtype: float64

In [20]:
new_df[["Age","Salary"]]

             Age    Salary
Atil    0.050685 -0.213228
Zeynep  0.553468 -0.329682
Atlas   1.034251  1.262323
Mehmet  0.751608 -0.062128

In [22]:
# if we want to access data by using rows we can use 
new_df.loc["Atil"]

Salary      -0.213228
Age          0.050685
Seniority   -0.809928
Name: Atil, dtype: float64

In [25]:
new_df.iloc[0] # by using index and location

Salary      -0.213228
Age          0.050685
Seniority   -0.809928
Name: Atil, dtype: float64

In [26]:
new_df

          Salary       Age  Seniority
Atil   -0.213228  0.050685  -0.809928
Zeynep -0.329682  0.553468  -0.964510
Atlas   1.262323  1.034251   0.875058
Mehmet -0.062128  0.751608   0.664133

In [28]:
new_df.iloc[:,0] # means select all rows and bring column by using index

Atil     -0.213228
Zeynep   -0.329682
Atlas     1.262323
Mehmet   -0.062128
Name: Salary, dtype: float64

In [29]:
# data manipulation

In [30]:
new_df["Age"]

Atil      0.050685
Zeynep    0.553468
Atlas     1.034251
Mehmet    0.751608
Name: Age, dtype: float64

In [32]:
# new_df["Extra"] there is no column like this one

In [33]:
new_df["Extra"] = 10 # it will assgin 10 to the all rows

In [34]:
new_df

          Salary       Age  Seniority  Extra
Atil   -0.213228  0.050685  -0.809928     10
Zeynep -0.329682  0.553468  -0.964510     10
Atlas   1.262323  1.034251   0.875058     10
Mehmet -0.062128  0.751608   0.664133     10

In [41]:
new_df.drop("Extra", axis=1) # we have to indicate axis

          Salary       Age  Seniority
Atil   -0.213228  0.050685  -0.809928
Zeynep -0.329682  0.553468  -0.964510
Atlas   1.262323  1.034251   0.875058
Mehmet -0.062128  0.751608   0.664133

In [42]:
new_df.loc["Ali"] = 55

In [44]:
new_df # to add a new row

           Salary        Age  Seniority  Extra
Atil    -0.213228   0.050685  -0.809928     10
Zeynep  -0.329682   0.553468  -0.964510     10
Atlas    1.262323   1.034251   0.875058     10
Mehmet  -0.062128   0.751608   0.664133     10
Ali     55.000000  55.000000  55.000000     55

In [45]:
new_df["Ali"]= 33

In [46]:
new_df

           Salary        Age  Seniority  Extra  Ali
Atil    -0.213228   0.050685  -0.809928     10   33
Zeynep  -0.329682   0.553468  -0.964510     10   33
Atlas    1.262323   1.034251   0.875058     10   33
Mehmet  -0.062128   0.751608   0.664133     10   33
Ali     55.000000  55.000000  55.000000     55   33

In [48]:
# now I want to delete Ali but whic one row or column that's why axis is important

In [51]:
new_df.drop("Ali", axis=1)

           Salary        Age  Seniority  Extra
Atil    -0.213228   0.050685  -0.809928     10
Zeynep  -0.329682   0.553468  -0.964510     10
Atlas    1.262323   1.034251   0.875058     10
Mehmet  -0.062128   0.751608   0.664133     10
Ali     55.000000  55.000000  55.000000     55

In [52]:
new_df.drop("Ali", axis=0)

          Salary       Age  Seniority  Extra  Ali
Atil   -0.213228  0.050685  -0.809928     10   33
Zeynep -0.329682  0.553468  -0.964510     10   33
Atlas   1.262323  1.034251   0.875058     10   33
Mehmet -0.062128  0.751608   0.664133     10   33

In [53]:
new_df # as you can see we could not delete to do this we can use inplace = True

           Salary        Age  Seniority  Extra  Ali
Atil    -0.213228   0.050685  -0.809928     10   33
Zeynep  -0.329682   0.553468  -0.964510     10   33
Atlas    1.262323   1.034251   0.875058     10   33
Mehmet  -0.062128   0.751608   0.664133     10   33
Ali     55.000000  55.000000  55.000000     55   33

In [54]:
new_df.drop("Ali",axis = 0, inplace = True)

In [55]:
new_df.drop("Ali",axis = 1, inplace = True)

In [56]:
new_df.drop("Extra",axis = 1, inplace = True)

In [57]:
new_df

          Salary       Age  Seniority
Atil   -0.213228  0.050685  -0.809928
Zeynep -0.329682  0.553468  -0.964510
Atlas   1.262323  1.034251   0.875058
Mehmet -0.062128  0.751608   0.664133

In [58]:
# we can use inplace almost in every  function

In [60]:
new_df.loc["Atlas"]

Salary       1.262323
Age          1.034251
Seniority    0.875058
Name: Atlas, dtype: float64

In [62]:
new_df.loc["Atlas"]["Salary"] # we can take intersection of a row and column

np.float64(1.262322781392654)

In [64]:
new_df.loc["Atlas","Salary"] = 100 # we can take intersection and we can change it

In [65]:
new_df

            Salary       Age  Seniority
Atil     -0.213228  0.050685  -0.809928
Zeynep   -0.329682  0.553468  -0.964510
Atlas   100.000000  1.034251   0.875058
Mehmet   -0.062128  0.751608   0.664133

In [66]:
new_df >0

        Salary   Age  Seniority
Atil     False  True      False
Zeynep   False  True      False
Atlas     True  True       True
Mehmet   False  True       True

In [68]:
boolean_frame = new_df>0
new_df[boolean_frame]

        Salary       Age  Seniority
Atil       NaN  0.050685        NaN
Zeynep     NaN  0.553468        NaN
Atlas    100.0  1.034251   0.875058
Mehmet     NaN  0.751608   0.664133

In [69]:
new_df[new_df["Salary"]>1]

       Salary       Age  Seniority
Atlas   100.0  1.034251   0.875058

In [70]:
new_df

            Salary       Age  Seniority
Atil     -0.213228  0.050685  -0.809928
Zeynep   -0.329682  0.553468  -0.964510
Atlas   100.000000  1.034251   0.875058
Mehmet   -0.062128  0.751608   0.664133

In [71]:
new_df.reset_index()

    index      Salary       Age  Seniority
0    Atil   -0.213228  0.050685  -0.809928
1  Zeynep   -0.329682  0.553468  -0.964510
2   Atlas  100.000000  1.034251   0.875058
3  Mehmet   -0.062128  0.751608   0.664133

In [74]:
reset_frame = new_df.reset_index() # to add new indexes

In [73]:
reset_frame

    index      Salary       Age  Seniority
0    Atil   -0.213228  0.050685  -0.809928
1  Zeynep   -0.329682  0.553468  -0.964510
2   Atlas  100.000000  1.034251   0.875058
3  Mehmet   -0.062128  0.751608   0.664133

In [75]:
reset_frame.loc[0]

index            Atil
Salary      -0.213228
Age          0.050685
Seniority   -0.809928
Name: 0, dtype: object

In [76]:
new_indices = ["Ati","Zey","Atl","Memo"]

In [77]:
new_df["NewIndex"] = new_indices

In [78]:
new_df

            Salary       Age  Seniority NewIndex
Atil     -0.213228  0.050685  -0.809928      Ati
Zeynep   -0.329682  0.553468  -0.964510      Zey
Atlas   100.000000  1.034251   0.875058      Atl
Mehmet   -0.062128  0.751608   0.664133     Memo

In [79]:
new_df.set_index("NewIndex",inplace=True)

In [80]:
new_df

              Salary       Age  Seniority
NewIndex
Ati        -0.213228  0.050685  -0.809928
Zey        -0.329682  0.553468  -0.964510
Atl       100.000000  1.034251   0.875058
Memo       -0.062128  0.751608   0.664133

In [81]:
new_df.loc["Ati"]

Salary      -0.213228
Age          0.050685
Seniority   -0.809928
Name: Ati, dtype: float64

In [82]:
# multi index

In [83]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [84]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [85]:
zipped_index = list(zip(first_index,inner_index))

In [86]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [88]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [89]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [90]:
sample_values = np.ones((6,2))

In [91]:
big_df = pd.DataFrame(sample_values,index=zipped_index,columns=["Age","Salary"])

In [92]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [93]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [95]:
# big_df.loc["Simpson"]["Homer"] this one is wrong to access inner index
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64